TEX_FILE = r"""%!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
%
%                          Auto Generated by tikzpy.
%
%
%%!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

\documentclass[12pt,letterpaper]{article}
\usepackage[left=0.3in, right=0.3in]{geometry}
\usepackage{amsmath, amsfonts, amssymb}
\usepackage[dvipsnames]{xcolor} % Colors, use dvipsnames for more color options
\usepackage{tikz-cd} % Diagrams
\usepackage{tikz} % General purpose graphics
\usepackage{pgfplots}
\usepackage{tikz-3dplot}

\usetikzlibrary{
    hobby,
    decorations.pathreplacing,
    decorations.markings
}

\begin{document}
\pagestyle{empty} % no page numbers

fillme

\end{document}
"""
